# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCDqLCNpKElzOJfPUJAUUhJuRr0-wI7C
"""



import nltk
from nltk.chat.util import Chat, reflections

try:
    # Ensure necessary NLTK data is downloaded
    nltk.download('punkt', quiet=True)
    print("NLTK 'punkt' downloaded successfully.")
except Exception as e:
    print(f"Error downloading NLTK data: {e}")

# Define a set of pairs for pattern-response pairs
pairs = [
    [
        r"hi|hello|hey",
        ["Hello! How can I assist you today?", "Hi there! How can I help?"]
    ],
    [
        r"how are you(.*)",
        ["I'm just a bot, but I'm doing great! How about you?", "I'm fine. How can I assist you?"]
    ],
    [
        r"what is your name(.*)",
        ["I'm ChatBot! What's your name?", "I am your virtual assistant. How can I assist you?"]
    ],
    [
        r"(.*) your name",
        ["I am called ChatBot. What's yours?", "You can call me ChatBot. How about you?"]
    ],
    [
        r"my name is (.*)",
        ["Nice to meet you, %1!", "Hello %1, how can I help you today?"]
    ],
    [
        r"what can you do(.*)",
        ["I can help answer your questions, assist with tasks, or just chat with you!", "I'm here to assist you with anything you need."]
    ],
    [
        r"bye|exit|quit",
        ["Goodbye! Have a great day!", "See you later! Take care!"]
    ],
    [
        r"(.*)",
        ["I'm sorry, I didn't understand that. Can you please elaborate?", "Interesting. Could you tell me more?"]
    ]
]

try:
    # Create a chatbot instance
    chatbot = Chat(pairs, reflections)
    print("Chatbot initialized successfully.")

    # Start the chatbot
    print("Hi! I am your chatbot. Type 'bye' to exit.")
    chatbot.converse()
except Exception as e:
    print(f"Error starting chatbot: {e}")

from google.colab import drive
drive.mount('/content/drive')